name: Bombadil Test 1

on:
  workflow_dispatch:

jobs:
  bombadil:
    runs-on: ubuntu-latest

    steps:
      - uses: antithesishq/bombadil-action@8c2027c9ff07c56f208c61fee60675b5faf01f8a
        with:
          origin: https://en.wikipedia.org
          specification: ./specification.ts
          version: 0.7.2
          time-limit: 1m
          exit-on-violation: true
          output-path: bombadil-output
